workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up code signing
        script: |
          # Insert your own method to set up signing here (automatic or manual)
          echo "Skipping code signing setup"
      - name: Build iOS app for release
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
